backend:
  name: git-gateway # git-gateway for production
  branch: master
  accept_roles:
    - admin
    - editor
  repo: yonydev/yonydev-v2

media_folder: "static/img"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: blog-entries
    label: Entradas de Blog
    folder: /src/pages/blog/
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: TemplateKey, name: templateKey, widget: hidden, default: blog-entry-page }
      - { label: Fecha, name: date, widget: date, format: "DD-MM-YYYY" }
      - { label: Título, name: title, widget: string }
      - { label: Contenido, name: content, widget: markdown }
      - { label: Timpo de Lectura, name: timeToRead, widget: string }

  - name: pages
    label: Páginas
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - { label: TemplateKey, name: templateKey, widget: hidden, default: home-page }
          - { label: Fecha, name: date, widget: date, format: "DD-MM-YYYY" }
          - { label: Título, name: title, widget: string }
          - { label: Ocupación, name: occupation, widget: list }
          - { label: Emoji, name: emoji, widget: list }
          - { label: Github URL, name: githubURL, widget: string }
          - { label: Instagram URL, name: instagramURL , widget: string }
          - { label: Twitter URL, name: twitterURL, widget: string }
          - { label: Linkedin URL, name: linkedinURL, widget: string }
          - { label: Medium URL, name: mediumURL, widget: string }

      - file: src/pages/blog.md
        label: Blog Page
        name: blog
        fields:
          - { label: TemplateKey, name: templateKey, widget: hidden, default: blog-page }
          - { label: Fecha, name: date, widget: date, format: "DD-MM-YYYY" }
          - { label: Título, name: title, widget: string }
          - label: Frases
            name: quotes
            widget: list
            fields:
              - { label: Contenido, name: content, widget: string }
              - { label: Autor, name: author, widget: string }
