backend:
  name: git-gateway # git-gateway for production
  branch: master
  repo: yonydev/yonydev-v2

media_folder: "static/img"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: pages
    label: Páginas
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - { label: TemplateKey, name: templateKey, widget: hidden, default: home-page }
          - { label: Fecha, name: date, widget: date, format: "DD-MM-YYYY" }
          - { label: Título, name: title, widget: string }
          - { label: Descripción, name: description, widget: string }
          - { label: Github URL, name: githubURL, widget: string }
          - { label: Instagram URL, name: instagramURL , widget: string }
          - { label: Twitter URL, name: twitterURL, widget: string }
          - { label: Linkedin URL, name: linkedinURL, widget: string }
          - { label: Medium URL, name: mediumURL, widget: string }
